server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 19971001

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: 365